### ISSUE TITLE
Give PO and SO admin permissions in Keycloak

### ISSUE THREAD

**Issue by jakemorr** [bcgov-c/wally#618]
**Describe the task**
Wally uses Keycloak to manage user permissions, could be done through Keycloak config

**Acceptance Criteria**
- [ ] PO and SO have the ability to provision access to Wally for users through Keycloak

**Additional context**
- Might be a PO task, done through Real administrator (Platform Services)
- Keycloak is a user authentication management tool that exists separate from the app itself
- When someone goes into the Wally app, it pings the Keycloak realm and Keycloak says whether the user is authenticated
- Keycloak has its own environments (ie. test-keycloak, prod-keycloak)
- Test - https://test.oidc.gov.bc.ca/auth/realms/iesymdnx/protocol/openid-connect/auth?client_id=security-admin-console&redirect_uri=https%3A%2F%2Ftest.oidc.gov.bc.ca%2Fauth%2Fadmin%2Fiesymdnx%2Fconsole%2F%23%2Frealms%2Fiesymdnx&state=48b9cbaf-8ffe-4ff4-8f1a-04d09401254c&response_mode=fragment&response_type=code&scope=openid&nonce=fcb56d1e-aa83-42ff-9259-7832614aff8b&code_challenge=Xr-nGb7_SUamd3bwoaL1q-s5Pul-VUzR0_DhwHRn3Eg&code_challenge_method=S256
- Prod- https://oidc.gov.bc.ca/auth/admin/iesymdnx/console/#/realms/iesymdnx

**Comment by LolandaE** [comment]
PO was able to get he permissions
