### ISSUE TITLE
Investigate if Certbot renewal is automated for Wally

### ISSUE THREAD

**Issue by LolandaE** [bcgov-c/wally#623]
**As a** *Service Owner* **I want** *automated certificate renewals* **So That** *our digital service doesn't display "your connection is not private" messaging*

**Additional Context**
- Example from Wildfire team:
https://github.com/bcgov/wps/tree/main/openshift/certbot

The cert expired in March and magically renewed (at a later date). Prevailing theory is that Certbot is automated. but for the wrong date.

**Acceptance Criteria**
- [ ] Is Certbot automated for Wally?
- [ ] If Certbot is automated for Wally, does the renewal date align with the cert expiration?

**Comment by Christopher-walsh22** [comment]
Certbot is set up for Wally vanity url 'wally.nrs.gov.bc.ca' with the certificate set for renewal August of each year. Certbot will run automated processes Sunday and Wednesday, and notify contact email when appropriate to pay for renewal.
