### ISSUE TITLE
Add Notations Layers - WALLY (High #1)

### ISSUE THREAD

**Issue by LolandaE** [bcgov-c/wally#645]
**Describe the task**
Water Allocation Restrictions layer has been discontinued and replaced with the following Notations layers:
	a. [Streams with Water Allocation Notations](https://catalogue.data.gov.bc.ca/dataset/streams-with-water-allocation-notations)
	b. [Aquifers with Water Allocation Notations](https://catalogue.data.gov.bc.ca/dataset/aquifers-with-water-allocation-notations)

**Acceptance Criteria**
- [x] New Notations layers added - **Streams with Water Allocation Notations** and **Aquifers with Water Allocation Notations**
- [x] Remove Water Allocation Restrictions layer from mapbox (iMap)

**Additional context**
- Source of the layers is BC Data Catalogue
- All layers on WALLY are togglable so we would want to follow that convention
- This helps flag problems

- The Water Allocation Restrictions no longer exists (screenshot below) and will be replaced with layers noted above

![image.png](https://images.zenhubusercontent.com/624f2ed04f19a502bdf062d9/29070a17-8074-4fb8-a56d-ec228b113789)

**Comment by dmitri-korin-bcps** [comment]
Need information on where exactly in BC Warehouse to look for the data for the new layers (Databases or URLs or API endpoints)

**Comment by LolandaE** [comment]
BC Data Catalogue URL added!

**Comment by Christopher-walsh22** [comment]
This layer being removed is causing the "Unimplemented type 4" error on the front end. 

Toggling this layer off stops the error from appearing in the console.
