### ISSUE TITLE
Update Wally Database for Gold

### ISSUE THREAD

**Issue by jakemorr** [bcgov-c/wally#657]
**Describe the task**
Update the existing database storing procedures to be able to handle the new Keycloak token structure

**Acceptance Criteria**
- [ ] Database can properly save user info from Keycloak

**Additional context**
How WALLY is saving things to the database is relatively unknown to me at the time of writing this other than the logic happens on the backend.  I do know the important tables relating to Keycloak having looked at it in openshift.  There is a user table and a user_map_layer table in the database.  

The user_map_layer table only uses idir's for saving/looking up info; that will still exist in gold but the field in the token could be a different name so that will possibly need to be updated.

The user layer is going to require a migration as the user_uuid is no longer going to exist in the gold realm; that is what will become the GUID.  I have uploaded the files that pair the UUID to the correct user's GUID from Zorin to the Dev Chat files section, and I believe Norris has experience writing a translation table for this kind of work so he will probably be able to give more info on how to go about doing this.

**Comment by LolandaE** [comment]
This work is being done in WALLY ticket #697
