### ISSUE TITLE
Split Backend Docker File into Two

### ISSUE THREAD

**Issue by LolandaE** [bcgov-c/wally#722]
**Describe the task**
Edit Dockerfile.dev.m1 in Wally backend and move everything from the beginning to 'cargo --release' to a separate Dockerfile. Build image locally using newly created Dockerfile.
Upload the created image to Artifactory.
Refer the image in Artifactory in Dockerfile.dev.m1. 
Build the final image using Dockerfile.dev.m1 

**Purpose**
Reduce Docker image build time for Wally backend. Currently it takes 45 min+ on local.

**Acceptance Criteria**
- [x] Build Wally image successfully
- [x] Image uploaded to Artifactory
- [x] Wally runs locally without issues
- [x] Test in Dev

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by sanjaytkbabu** [comment]
wbt-rust:1.0 image has been built locally.
obtained artifactory svc account creds from oc wally namespace secrets
artifactory project for Wally requested through oc
waiting for response from Platform Services Team to proceed with uploading the image to artifactory
ref:https://docs.developer.gov.bc.ca/setup-artifactory-project-repository/
https://docs.developer.gov.bc.ca/setup-artifactory-service-account/

**Comment by sanjaytkbabu** [comment]
# Wally tools namespace
'oc project d1b5d2-tools`

**Comment by sanjaytkbabu** [comment]
pushed to git: https://github.com/bcgov-c/wally/tree/feat/722

**Comment by sanjaytkbabu** [comment]
Artifactory project created: https://artifacts.developer.gov.bc.ca/ui/builds?projectKey=wd1b

**Comment by sanjaytkbabu** [comment]
Follow https://docs.developer.gov.bc.ca/push-pull-artifacts-artifactory/#pull-docker-images-from-artifactory 
to setup pull secret

**Comment by sanjaytkbabu** [comment]
Deployed to Staging. Jenkins log: https://wally-jenkins.apps.silver.devops.gov.bc.ca/job/Wally/job/master/117/console
App link: https://wally-staging.apps.silver.devops.gov.bc.ca/
