### ISSUE TITLE
Cert Renewal (Expires November 6th) - WALLY

### ISSUE THREAD

**Issue by jakemorr** [bcgov-c/wally#726]
**Describe the task**
 Entrust Certificate expired August 30, 2023. Certbot was down so we implemented a Let's Encrypt Cert for 90 days while we wait to see if Certbot will be fixed. if Certbot is fixed we will need to renew an entrust cert then we proceed, if certbot is not up we will have to decide what our path forward is at that point.

**Purpose**
This is required so that the end user doesn't experience a "your connection is not private" warning message (even though they can still click through and use the application).

**Acceptance Criteria**
- [ ] iStore request created with billing information
- [ ] Certificate is renewed and end user arrives at homepage with no warning message displayed

**Additional Context**
- Need to look into why it doesn't send notifications to the Sustainment Team inbox about renewals, etc.
- Might need to look into billing and duplicate request

**Comment by LolandaE** [comment]
Check status of Entrust/CertBot at the beginning of October so there's some lead time before cert expires.

**Comment by davidclaveau** [comment]
For temporary certificate renewals: https://apps.nrs.gov.bc.ca/int/confluence/display/DEVGUILD/Generating+a+CSR?

**Comment by davidclaveau** [comment]
Sent an email to Infrastructure.MiddleTier@gov.bc.ca regarding next steps.

According to [the Confluence page](https://apps.nrs.gov.bc.ca/int/confluence/display/DEVGUILD/Generating+a+CSR#GeneratingaCSR-HostedonOpenshift), it seems like we can use the steps under “Host on Openshift” to start the renewal process and generate the cert manually. However, we also noticed on another page that domains using “.nrs.gov.bc.ca” are handled automatically by the NRIDS Infrastructure MiddleTier team.

**Comment by davidclaveau** [comment]
Sent an email to Infrastructure.MiddleTier@gov.bc.ca regarding next steps.

According to [the Confluence page](https://apps.nrs.gov.bc.ca/int/confluence/display/DEVGUILD/Generating+a+CSR#GeneratingaCSR-HostedonOpenshift), it seems like we can use the steps under “Host on Openshift” to start the renewal process and generate the cert manually. However, we also noticed on [another page](https://apps.nrs.gov.bc.ca/int/confluence/display/DEVGUILD/SSL+Certificates) that domains using “.nrs.gov.bc.ca” are handled automatically by the NRIDS Infrastructure MiddleTier team, so it _might_ not require too much work on our end.

**Comment by jakemorr** [comment]
Jake to get TCA Account Code and expense authority

**Comment by davidclaveau** [comment]
NRIDS accepted the request, and forwarded their request through My Service Center (REQ0441920). CC'd Sustainment Team's email for notification.

**Comment by davidclaveau** [comment]
Successfully updated WALLY's certs and keys to use Entrust. The certificate is good until Oct. 30th, 2024.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnloQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b7d3c82c68ba1d221f4cd485fbdaa52226a573c/Screenshot%202023-11-03%20at%201.21.41%E2%80%AFPM.png)

**Comment by davidclaveau** [comment]
Successfully updated WALLY's certs and keys to use Entrust. The certificate is good until Oct. 30th, 2024. There are steps to creating a certificate in the Sustainment Team's Dev Chat Files called "Cert Renewal.docx"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnloQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b7d3c82c68ba1d221f4cd485fbdaa52226a573c/Screenshot%202023-11-03%20at%201.21.41%E2%80%AFPM.png)

**Comment by davidclaveau** [comment]
Successfully updated WALLY's certs and keys to use Entrust. The certificate is good until Oct. 30th, 2024. There are steps to creating a certificate in the Sustainment Team's Dev Chat Files called "Entrust Cert Creation.docx"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnloQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b7d3c82c68ba1d221f4cd485fbdaa52226a573c/Screenshot%202023-11-03%20at%201.21.41%E2%80%AFPM.png)
